#!/usr/bin/env python3
"""Generate paper/generated/*.tex from authoritative M5.10 result artifacts."""
from __future__ import annotations

import csv
import hashlib
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GUAR = ROOT / "results" / "tables" / "m510_guarantee_matrix.csv"
SENS = ROOT / "results" / "tables" / "m510_assumption_sensitivity.csv"
OUT_MACROS = ROOT / "paper" / "generated" / "result_macros.tex"
OUT_PROV = ROOT / "paper" / "generated" / "provenance.tex"
OUT_PROP = ROOT / "paper" / "tables" / "property_summary.tex"
OUT_RST = ROOT / "paper" / "tables" / "reset_comparison.tex"
OUT_SENS = ROOT / "paper" / "tables" / "assumption_sensitivity.tex"
OUT_FORMAL = ROOT / "paper" / "tables" / "formal_results.tex"
OUT_CLAIMS = ROOT / "paper" / "tables" / "claims_evidence.tex"


def git_head() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
        ).strip()
    except Exception:
        return "unknown"


def read_csv(path: Path) -> list[dict]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def esc(s: str) -> str:
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("&", "\\&")
        .replace("%", "\\%")
    )


def safe_macro_id(pid: str) -> str:
    digit_words = "Zero One Two Three Four Five Six Seven Eight Nine".split()
    out: list[str] = []
    for c in pid:
        if c.isdigit():
            out.append(digit_words[int(c)])
        elif c in "-_":
            continue
        else:
            out.append(c)
    return "".join(out)


def macro_name(pid: str, field: str) -> str:
    return f"\\Evidence{safe_macro_id(pid)}{field}"


def status_label(row: dict, col: str) -> str:
    v = row.get(col, "NOT_RUN")
    c = row.get("classification", v)
    if col == "pdr_result" and v == "FAIL":
        return f"{v} (raw; see classification: {c})"
    return v


def write_macros(rows: list[dict]) -> None:
    lines = [
        "% Auto-generated by scripts/analysis/generate_paper_artifacts.py",
        f"% Do not edit manually",
        "",
        f"\\newcommand{{\\GitCommitMFiveTen}}{{681b2bd}}",
        f"\\newcommand{{\\GitCommitCurrent}}{{{git_head()}}}",
        f"\\newcommand{{\\EvidenceFreezeDate}}{{{datetime.now(timezone.utc).strftime('%Y-%m-%d')}}}",
        "",
    ]
    for r in rows:
        pid = r["property_id"]
        lines.append(f"\\newcommand{{{macro_name(pid, 'Sim')}}}{{{esc(r.get('simulation_result',''))}}}")
        lines.append(f"\\newcommand{{{macro_name(pid, 'Bmc')}}}{{{esc(r.get('bmc_result',''))}}}")
        lines.append(f"\\newcommand{{{macro_name(pid, 'Pdr')}}}{{{esc(status_label(r, 'pdr_result'))}}}")
        lines.append(f"\\newcommand{{{macro_name(pid, 'Class')}}}{{{esc(r.get('classification',''))}}}")
        lines.append("")
    OUT_MACROS.parent.mkdir(parents=True, exist_ok=True)
    OUT_MACROS.write_text("\n".join(lines) + "\n")


def write_provenance() -> None:
    script_hash = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()[:12]
    text = f"""% Auto-generated provenance
\\newcommand{{\\ProvenanceCommit}}{{{git_head()}}}
\\newcommand{{\\ProvenanceScriptHash}}{{{script_hash}}}
\\newcommand{{\\ProvenanceGenerated}}{{{datetime.now(timezone.utc).isoformat()}}}
\\newcommand{{\\ProvenanceGuaranteeCsv}}{{results/tables/m510\\_guarantee\\_matrix.csv}}
\\newcommand{{\\ProvenanceSensitivityCsv}}{{results/tables/m510\\_assumption\\_sensitivity.csv}}
"""
    OUT_PROV.write_text(text)


MAIN_PAPER_PROPS = [
    "SP-02", "SP-04", "SP-06", "SP-08-RST-A", "SP-08-RST-B", "M57-FP-04-FIX2"
]


def write_property_summary(rows: list[dict]) -> None:
    by_id = {r["property_id"]: r for r in rows}
    lines = [
        "% Auto-generated property summary (main paper subset)",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Representative security properties: simulation vs formal methods. "
        "PDR column shows raw engine status where applicable; scientific classification is separate.}",
        "\\label{tab:property-summary}",
        "\\small",
        "\\begin{tabularx}{\\linewidth}{@{}lXXXXl@{}}",
        "\\toprule",
        "Property & Sim & BMC & PDR/Induct. & Scientific status \\\\",
        "\\midrule",
    ]
    for pid in MAIN_PAPER_PROPS:
        r = by_id.get(pid)
        if not r:
            continue
        pdr = status_label(r, "pdr_result")
        lines.append(
            f"{esc(pid)} & {esc(r['simulation_result'])} & {esc(r['bmc_result'])} & "
            f"{esc(pdr)} & {esc(r['classification'])} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabularx}", "\\end{table}"]
    OUT_PROP.write_text("\n".join(lines) + "\n")


def write_reset_comparison(rows: list[dict]) -> None:
    by_id = {r["property_id"]: r for r in rows}
    ra, rb = by_id.get("SP-08-RST-A", {}), by_id.get("SP-08-RST-B", {})
    lines = [
        "% Auto-generated reset model comparison",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{RST-A (fail-open) vs RST-B (fail-closed) under SP-08. "
        "RST-A counterexample is classified as reset-assumption dependency, not a vulnerability.}",
        "\\label{tab:reset-comparison}",
        "\\begin{tabular}{@{}lllll@{}}",
        "\\toprule",
        "Model & Default & DMA before \\texttt{secure\\_ready} & Formal & Classification \\\\",
        "\\midrule",
        f"RST-A & fail-open & reachable (CE) & {esc(ra.get('bmc_result',''))} & "
        f"{esc(ra.get('classification',''))} \\\\",
        f"RST-B & fail-closed & unreachable & k-induction proof & "
        f"{esc(rb.get('classification',''))} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    OUT_RST.write_text("\n".join(lines) + "\n")


def write_assumption_sensitivity(rows: list[dict]) -> None:
    subset = rows[:6]
    lines = [
        "% Auto-generated assumption sensitivity (main paper subset)",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Assumption sensitivity (subset). Full matrix in appendix.}",
        "\\label{tab:assumption-sensitivity}",
        "\\small",
        "\\begin{tabularx}{\\linewidth}{@{}lXXl@{}}",
        "\\toprule",
        "Assumption & Baseline & If removed/weakened & Classification \\\\",
        "\\midrule",
    ]
    for r in subset:
        lines.append(
            f"{esc(r.get('assumption_id',''))} & {esc(r.get('baseline_status',''))} & "
            f"{esc(r.get('weakened_status',''))} & {esc(r.get('classification',''))} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabularx}", "\\end{table}"]
    OUT_SENS.write_text("\n".join(lines) + "\n")


def write_formal_results(rows: list[dict]) -> None:
    lines = [
        "% Auto-generated formal results table",
        "\\input{tables/property_summary.tex}",
        "\\input{tables/reset_comparison.tex}",
    ]
    OUT_FORMAL.write_text("\n".join(lines) + "\n")


def write_claims_tex(claims: list[dict]) -> None:
    lines = [
        "% Auto-generated claims-to-evidence (main paper subset)",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Claims-to-evidence mapping (subset). Full register: \\texttt{results/m6/claims\\_evidence.csv}.}",
        "\\label{tab:claims-evidence}",
        "\\footnotesize",
        "\\begin{tabularx}{\\textwidth}{@{}lXll@{}}",
        "\\toprule",
        "ID & Claim & Status & Evidence \\\\",
        "\\midrule",
    ]
    for c in claims[:8]:
        lines.append(
            f"{esc(c['claim_id'])} & {esc(c['claim_text'][:80])}... & "
            f"{esc(c['scientific_status'])} & {esc(c['evidence_file'][:40])} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabularx}", "\\end{table*}"]
    OUT_CLAIMS.write_text("\n".join(lines) + "\n")


CLAIMS = [
    {
        "claim_id": "CL-01",
        "claim_text": "CPU unauthorized protected-memory writes blocked by modeled PMP under stated assumptions",
        "property_id": "SP-02",
        "scientific_status": "FORMAL_PROOF",
        "evidence_type": "formal+simulation",
        "evidence_file": "results/tables/m510_guarantee_matrix.csv",
        "reproduction_command": "make m510-matrix",
        "git_commit": "681b2bd",
        "limitations": "Abstract CPU; FA-03..FA-08",
        "paper_section": "07_results",
    },
    {
        "claim_id": "CL-02",
        "claim_text": "Unauthorized DMA protected-memory writes blocked by modeled IOPMP under stated assumptions",
        "property_id": "SP-04",
        "scientific_status": "FORMAL_PROOF",
        "evidence_type": "formal+simulation",
        "evidence_file": "results/tables/m510_guarantee_matrix.csv",
        "reproduction_command": "make m510-matrix",
        "git_commit": "681b2bd",
        "limitations": "Research IOPMP model; FA-02,FA-05",
        "paper_section": "07_results",
    },
    {
        "claim_id": "CL-03",
        "claim_text": "Fail-open reset model permits reachable early-DMA protected-memory state before secure_ready",
        "property_id": "SP-08-RST-A",
        "scientific_status": "RESET_ASSUMPTION_DEPENDENCY",
        "evidence_type": "formal counterexample",
        "evidence_file": "results/formal/counterexamples/SP-08/",
        "reproduction_command": "cd formal/sby && sby -f -d ../../results/formal/sp08_reset sp08_reset.sby",
        "git_commit": "681b2bd",
        "limitations": "Model-level; not a product vulnerability claim",
        "paper_section": "07_results",
    },
    {
        "claim_id": "CL-04",
        "claim_text": "Fail-closed reset model excludes corresponding unsafe state under formal model and assumptions",
        "property_id": "SP-08-RST-B",
        "scientific_status": "FORMAL_PROOF",
        "evidence_type": "k-induction (SymbiYosys smtbmc z3)",
        "evidence_file": "results/formal/sp08_rstb_prove/logfile.txt",
        "reproduction_command": "make m510-formal",
        "git_commit": "681b2bd",
        "limitations": "RST-B defaults; FA-01,FA-07",
        "paper_section": "07_results",
    },
    {
        "claim_id": "CL-05",
        "claim_text": "Requester identity participates in access-control decisions",
        "property_id": "SP-06",
        "scientific_status": "PASS (simulation)",
        "evidence_type": "directed simulation",
        "evidence_file": "results/tables/security_matrix.csv",
        "reproduction_command": "make m2",
        "git_commit": "681b2bd",
        "limitations": "Simulation only for SP-06; FA-02",
        "paper_section": "07_results",
    },
    {
        "claim_id": "CL-06",
        "claim_text": "M57-FP-04 write-binding on repaired RTL has bounded evidence, not unbounded proof",
        "property_id": "M57-FP-04-FIX2",
        "scientific_status": "BOUNDED_EVIDENCE",
        "evidence_type": "Verilator+BMC ENV-4; PDR raw FAIL",
        "evidence_file": "results/tables/m510_guarantee_matrix.csv",
        "reproduction_command": "make m59-bmc",
        "git_commit": "681b2bd",
        "limitations": "M59-FA-01..12; PDR not proved; M5.8 CE was harness artifact",
        "paper_section": "07_results",
    },
]


def write_claims_csv_md() -> None:
    fields = list(CLAIMS[0].keys())
    csv_path = ROOT / "results" / "m6" / "claims_evidence.csv"
    md_path = ROOT / "results" / "m6" / "claims_evidence.md"
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(CLAIMS)
    md_lines = ["# Claims-to-evidence register (M6)\n"]
    for c in CLAIMS:
        md_lines.append(f"## {c['claim_id']}\n")
        for k, v in c.items():
            md_lines.append(f"- **{k}**: {v}")
        md_lines.append("")
    md_path.write_text("\n".join(md_lines))


def ensure_dirs() -> None:
    for d in (OUT_MACROS.parent, OUT_PROP.parent, OUT_RST.parent, OUT_SENS.parent,
              OUT_FORMAL.parent, OUT_CLAIMS.parent):
        d.mkdir(parents=True, exist_ok=True)


def main() -> int:
    ensure_dirs()
    rows = read_csv(GUAR)
    sens = read_csv(SENS)
    write_macros(rows)
    write_provenance()
    write_property_summary(rows)
    write_reset_comparison(rows)
    write_assumption_sensitivity(sens)
    write_formal_results(rows)
    write_claims_csv_md()
    write_claims_tex(CLAIMS)
    print(f"Generated paper artifacts under {ROOT / 'paper'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
